data_source GLACIER_DATASOURCE:
  type: snowflake
  connection:
    username: ${SNOWFLAKE_USER}
    password: ${SNOWFLAKE_PASSWORD}
    # provide the account in the format xy12345.eu-central-1
    account: ${SNOWFLAKE_ACCOUNT}
    database: ${SNOWFLAKE_DB}
    warehouse: ${SNOWFLAKE_WH}
    # if your connection times out you may need to adjust the timeout value
    connection_timeout: 300
    role: ${SNOWFLAKE_ROLE}
    client_session_keep_alive:
    session_parameters:
      QUERY_TAG: soda-queries
      QUOTED_IDENTIFIERS_IGNORE_CASE: false
  schema: ${SNOWFLAKE_SCHEMA}